In [2]:
import pandas as pd 

df = pd.read_csv('en openfoodfacts org products.csv')

In [3]:
df.head(5)

,code,product_name,quantity,packaging_en,brands_en,categories_en,origins_en,labels_en,countries_en,nutriscore_grade,pnns_groups_1,pnns_groups_2,food_groups_en,environmental_score_score,environmental_score_grade,main_category_en,carbon-footprint_100g,carbon-footprint-from-meat-or-fish_100g
0,301762042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Finland,unknown,unknown,unknown,NaN,NaN,NaN,NaN,NaN,NaN
1,2045652893,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Finland,unknown,unknown,unknown,NaN,NaN,NaN,NaN,NaN,NaN
2,3017620422,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Finland,unknown,unknown,unknown,NaN,NaN,NaN,NaN,NaN,NaN
3,490000030464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Finland,unknown,unknown,unknown,NaN,NaN,NaN,NaN,NaN,NaN
4,11702334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Finland,unknown,unknown,unknown,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df['pnns_groups_2'].value_counts()

pnns_groups_2
unknown                             8484
Sweets                               510
Biscuits and cakes                   382
Milk and yogurt                      363
One-dish meals                       283
Dairy desserts                       279
Bread                                251
Cheese                               194
Dressings and sauces                 189
Breakfast cereals                    185
Chocolate products                   176
Meat                                 169
Cereals                              162
Sweetened beverages                  148
Ice cream                            131
Processed meat                       128
Plant-based milk substitutes         113
Vegetables                            92
Artificially sweetened beverages      83
Alcoholic beverages                   80
Unsweetened beverages                 69
Fats                                  68
Fish and seafood                      65
Appetizers                            64
Salty and fatty products              61
Pizza pies and quiches                59
Fruits                                53
Legumes                               46
Fruit juices                          42
Nuts                                  36
Eggs                                  31
Potatoes                              28
Waters and flavored waters            25
Sandwiches                            24
Soups                                 24
Dried fruits                          20
Teas and herbal teas and coffees      12
Pastries                               4
Fruit nectars                          1
Name: count, dtype: int64

In [5]:
df_category = df['main_category_en'].value_counts()

df_category.to_csv('test.csv')

In [6]:
df['pnns_groups_1'].value_counts()

pnns_groups_1
unknown                    8484
Sugary snacks              1072
Milk and dairy products     967
Cereals and potatoes        672
Beverages                   493
Fish Meat Eggs              393
Composite foods             366
Fat and sauces              257
Fruits and vegetables       189
Salty snacks                161
Alcoholic beverages          80
Name: count, dtype: int64

In [7]:
dividing = df['pnns_groups_2'].value_counts()

dividing.to_csv('future_dividing.csv')

In [8]:
df['pnns_groups_1'].value_counts()

pnns_groups_1
unknown                    8484
Sugary snacks              1072
Milk and dairy products     967
Cereals and potatoes        672
Beverages                   493
Fish Meat Eggs              393
Composite foods             366
Fat and sauces              257
Fruits and vegetables       189
Salty snacks                161
Alcoholic beverages          80
Name: count, dtype: int64

In [9]:
sample = df[df['pnns_groups_2'] == 'Milk and yogurt']

sample.to_csv('sample.csv')

In [10]:
df[df['pnns_groups_2'] == 'Fruit nectars'].sample(1)

,code,product_name,quantity,packaging_en,brands_en,categories_en,origins_en,labels_en,countries_en,nutriscore_grade,pnns_groups_1,pnns_groups_2,food_groups_en,environmental_score_score,environmental_score_grade,main_category_en,carbon-footprint_100g,carbon-footprint-from-meat-or-fish_100g
8574,6470910139680,Nectar multifruits - €.C.O.+ - 2L,2000.0g,NaN,C-o,"Plant-based foods and beverages,Beverages,Plan...",NaN,NaN,Finland,unknown,Beverages,Fruit nectars,"Beverages,Fruit nectars",NaN,NaN,Multifruit nectars,NaN,NaN

IF pnns_groups_2 == 'Milk and yogurt':
    IF categories_en IN 'Yogurt':
        carbon-footprint_100g = 1.5
    ELIF categories_en IN 'Tea' AND packaging_en IN 'Paperboard':
        carbon-footprint_100g = 2
    ELIF categories_en IN 'Tea' AND packaging_en IN 'Plastic':
        carbon-footprint_100g = 10
    ELSE:
        carbon-footprint_100g = 2

IF pnns_groups_2 == 'Milk and yogurt':
        carbon-footprint_100g = 2

In [11]:
df_sweet = df[df['pnns_groups_2'] == 'Sweets']

df_sweet.shape

(510, 18)

In [12]:
df.columns

Index(['code', 'product_name', 'quantity', 'packaging_en', 'brands_en',
       'categories_en', 'origins_en', 'labels_en', 'countries_en',
       'nutriscore_grade', 'pnns_groups_1', 'pnns_groups_2', 'food_groups_en',
       'environmental_score_score', 'environmental_score_grade',
       'main_category_en', 'carbon-footprint_100g',
       'carbon-footprint-from-meat-or-fish_100g'],
      dtype='object')

In [13]:
# df.loc[df['pnns_groups_2'] == 'Sweets', 'carbon-footprint_100g'] = 2.95


# df.loc[df['pnns_groups_2'] == 'Sweets', 'carbon-footprint_100g'] = 2

df.drop(df[df['pnns_groups_1'] == "unknown"].index, inplace=True)
df.dropna(subset=['pnns_groups_1'], inplace=True)

df.shape

(4650, 18)

In [14]:
df_co2 = pd.read_csv('https://raw.githubusercontent.com/Phi-project3/finalproject/refs/heads/main/dossier/donnees/source/category_schema/products_category_schema_v1.csv', sep=';')

df_co2.sample(5)

,source_product_category,category_name,kg_CO2_min,kg_CO2_max,average
22,Other vegetables,Legumes,0.1,3.0,1.550
2,Juices and seasonal drinks,Fruit nectars,0.6,1.3,0.950
69,https://myemissions.co/resources/food-carbon-f...,Dressings and sauces,NaN,NaN,4.607
57,Chocolate and other sweets,Chocolate products,1.7,4.2,2.950
4,Soft drinks and energy drinks,Artificially sweetened beverages,0.1,1.0,0.550

In [15]:
df_merged = df.merge(df_co2[['category_name', 'average']], how='left', left_on='pnns_groups_2', right_on='category_name')

df_merged.drop(columns=['category_name', 'carbon-footprint_100g', 'carbon-footprint-from-meat-or-fish_100g'], inplace=True)

df_merged.rename(columns={'average': 'carbon-footprint_100g'}, inplace=True)

df_merged.sample(5)

,code,product_name,quantity,packaging_en,brands_en,categories_en,origins_en,labels_en,countries_en,nutriscore_grade,pnns_groups_1,pnns_groups_2,food_groups_en,environmental_score_score,environmental_score_grade,main_category_en,carbon-footprint_100g
3292,5029396000895,Connoisseurs Tonic Water,500 ml,Bottle,Cask-as,"Beverages and beverages preparations,Beverages...",NaN,No gluten,"Belgium,Finland,Germany",c,Beverages,Sweetened beverages,"Beverages,Sweetened beverages",NaN,not-applicable,Tonic water,0.55
700,6410381081484,Sips - Salt & Pepper,325g,NaN,Taffel,"Plant-based foods and beverages,Plant-based fo...",NaN,NaN,Finland,d,Composite foods,One-dish meals,"Composite foods,One-dish meals",NaN,NaN,Flavoured potato crisps,2.95
4172,6414000001754,Sirkku palasokeri,750 g,Container,Dan-sukker,"Sweeteners,Sugars",NaN,fi:valmistettu-suomessa,Finland,e,Sugary snacks,Sweets,"Sugary snacks,Sweets",NaN,NaN,Sugars,2.95
570,6405372000452,Julia 10,440 g,NaN,Juustoportti,"Dairies,Fermented foods,Fermented milk product...",NaN,NaN,Finland,unknown,Fat and sauces,Fats,"Fats and sauces,Fats",NaN,NaN,Milkfat,6.05
866,6416453014374,Karl Fazer rouhea keksi,180 g,NaN,Fazer,"Snacks,Sweet snacks,Cocoa and its products,Cho...",NaN,NaN,Finland,e,Sugary snacks,Chocolate products,"Sugary snacks,Chocolate products",NaN,NaN,Milk chocolate bar,2.95

In [16]:
# df[df['pnns_groups_2'] == 'Soups']

df[df['code'] == 20043032]

,code,product_name,quantity,packaging_en,brands_en,categories_en,origins_en,labels_en,countries_en,nutriscore_grade,pnns_groups_1,pnns_groups_2,food_groups_en,environmental_score_score,environmental_score_grade,main_category_en,carbon-footprint_100g,carbon-footprint-from-meat-or-fish_100g
7413,20043032,Easter Egg Mix,NaN,NaN,Fresh-easy,"Meals,Soups",NaN,NaN,"Finland,United States",e,Composite foods,One-dish meals,"Composite foods,One-dish meals",NaN,NaN,Soups,NaN,NaN

In [17]:
df.columns

Index(['code', 'product_name', 'quantity', 'packaging_en', 'brands_en',
       'categories_en', 'origins_en', 'labels_en', 'countries_en',
       'nutriscore_grade', 'pnns_groups_1', 'pnns_groups_2', 'food_groups_en',
       'environmental_score_score', 'environmental_score_grade',
       'main_category_en', 'carbon-footprint_100g',
       'carbon-footprint-from-meat-or-fish_100g'],
      dtype='object')